# -*- coding: utf-8 -*-
"""
@author: Adrián Revuelta Cuauhtli
"""

__version__ = '0.9'

_UPDATE_LABEL_OFFSET = False

LINE_WIDTH = 2.0
    
PLACE_RADIUS = 25
PLACE_LABEL_PADDING = PLACE_RADIUS + 15

TRANSITION_HALF_LARGE = 40
TRANSITION_HALF_SMALL = 7.5
TRANSITION_HORIZONTAL_LABEL_PADDING = TRANSITION_HALF_SMALL + 15
TRANSITION_VERTICAL_LABEL_PADDING = TRANSITION_HALF_LARGE + 15